name: goscale
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
